S4 Header and footer
Zeroya/react-food-shop-app pull request #4
Opened 2022-10-04 15:54 UTC by Zeroya

2022-10-04 16:30 UTC, Yuliia143 commented on src/components/Header/Header.tsx
> +          <p>info@freshnesecom.com</p>
I don't think that phone number and email should be as p

2022-10-04 16:30 UTC, Yuliia143 commented on src/components/Header/Header.tsx
> +          <p>Careers</p>
Seems there should be links

2022-10-04 16:30 UTC, Yuliia143 commented on src/components/Header/Header.tsx
> +          <ShoppingCartOutlined style={{ fontSize: "30px", paddingTop: "8px" }} />
inline styles

2022-10-04 16:30 UTC, Yuliia143 commented on src/components/Header/Header.tsx
> +          return (
skip return

2022-10-04 16:30 UTC, Yuliia143 commented on src/constants/constants.ts
> +export const tagsArr: Array<string> = [
Seems it's mocked data, should be in another file

2022-10-04 16:30 UTC, Yuliia143 commented on src/components/Footer/Footer.module.scss
> +      color: #6A983C;
Create file for colors

2022-10-04 16:30 UTC, Yuliia143 commented on src/components/Footer/Footer.module.scss
> +        &>p {
Don't like these selectors, try to create classes more

2022-10-04 16:30 UTC, Yuliia143 commented on src/components/Footer/Footer.tsx
> +            return (
Follow one code style

2022-10-05 07:51 UTC, Zeroya commented on src/components/Header/Header.tsx
> +          <p>info@freshnesecom.com</p>
Fixed

2022-10-05 07:52 UTC, Zeroya commented on src/components/Header/Header.tsx
> +          <p>Careers</p>
In general, we don't have such pages, but I posted a link to existing ones

2022-10-05 07:53 UTC, Zeroya commented on src/components/Header/Header.tsx
> +          return (
Fixed

2022-10-05 07:53 UTC, Zeroya commented on src/components/Header/Header.tsx
> +          <ShoppingCartOutlined style={{ fontSize: "30px", paddingTop: "8px" }} />
moved to scss file

2022-10-05 07:54 UTC, Zeroya commented on src/constants/constants.ts
> +export const tagsArr: Array<string> = [
Created a folder for mocked data

2022-10-05 07:55 UTC, Zeroya commented on src/components/Footer/Footer.tsx
> +            return (
You mean return in map ?

2022-10-05 08:59 UTC, Yuliia143 commented on src/components/Footer/Footer.tsx
> +            return (
Yep
Sometimes you have it, sometimes don't

2022-10-05 09:01 UTC, Zeroya commented on src/components/Footer/Footer.tsx
> +            return (
I already changed it

2022-10-05 09:03 UTC, Yuliia143 requested changes
:)

2022-10-05 09:42 UTC, Zeroya commented on src/components/Header/Header.tsx
> +          <ShoppingCartOutlined style={{ fontSize: "30px", paddingTop: "8px" }} />
I think i got it, its inline styles about which I forgot , correct ?

2022-10-05 11:18 UTC, Yuliia143 commented on src/components/Header/Header.tsx
> +          <ShoppingCartOutlined style={{ fontSize: "30px", paddingTop: "8px" }} />
You're right

2022-10-05 11:59 UTC, Yuliia143 approved these changes

2022-10-05 12:01 UTC, merged